name: ICDAR_comp_19
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.6=h1de35cc_1002
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37hccf1714_0
  - cycler=0.10.0=py_1
  - freetype=2.10.0=h24853df_0
  - intel-openmp=2019.3=199
  - jpeg=9c=h1de35cc_1001
  - kiwisolver=1.0.1=py37h04f5b5a_1002
  - libblas=3.8.0=6_openblas
  - libcblas=3.8.0=6_openblas
  - libcxx=8.0.0=2
  - libcxxabi=8.0.0=2
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=3.0.1=0
  - liblapack=3.8.0=6_openblas
  - libpng=1.6.37=h2573ce8_0
  - libtiff=4.0.10=h79f4b77_1001
  - matplotlib=3.0.3=py37_1
  - matplotlib-base=3.0.3=py37habd5b94_1
  - mkl=2019.3=199
  - ncurses=6.1=h0a44026_1002
  - ninja=1.9.0=h04f5b5a_0
  - numpy=1.16.3=py37hdf140aa_0
  - olefile=0.46=py_0
  - openblas=0.3.5=h436c29b_1001
  - openssl=1.1.1b=h01d97ff_2
  - pillow=6.0.0=py37h7095ceb_0
  - pip=19.1=py37_0
  - pycparser=2.19=py37_1
  - pyparsing=2.4.0=py_0
  - python=3.7.3=h0d93f26_0
  - python-dateutil=2.8.0=py_0
  - pytorch=1.0.1=py3.7_2
  - readline=7.0=hcfe32e1_1001
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_1000
  - sqlite=3.26.0=h1765d9f_1001
  - tk=8.6.9=ha441bb4_1001
  - torchvision=0.2.2=py_3
  - tornado=6.0.2=py37h01d97ff_0
  - wheel=0.33.1=py37_0
  - xz=5.2.4=h1de35cc_1001
  - zlib=1.2.11=h1de35cc_1004
prefix: /Users/voegtlil/miniconda3/envs/ICDAR_comp_19

